Fix inconsistent formatting in README.md
salman-bhai/hello-world pull request #127
Opened 2017-09-29 02:59 UTC by grrttedwards

In the Scala README.md, there were some inconsistencies in the formatting. The sub-headers under Mac installation were enormous H1 headers, and the code to run at the bottom was in `inline code form`.

2017-09-29 09:53 UTC, sbshah97 requested changes
Make the required changes on the same branch so that it gets pushed to this PR!

2017-09-29 09:53 UTC, salman-bhai commented on Scala/README.md
> +    echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
Replace the entire thing with this
(```)
Check out how to write Markdown for multi-line code!

2017-09-29 09:53 UTC, salman-bhai commented on Scala/README.md
> +    curl https://bintray.com/sbt/rpm/rpm | sudo tee/etc/yum.repos.d/bintray-sbt-rpm.repo
Replace the entire thing with this
(```)
Check out how to write Markdown for multi-line code!

2017-09-29 09:53 UTC, salman-bhai commented on Scala/README.md
> +    $ brew install sbt
Replace the entire thing with this
(```)
Check out how to write Markdown for multi-line code!

2017-09-29 09:53 UTC, salman-bhai commented on Scala/README.md
> +    scala hello-world.scala
Replace the entire thing with this
(```)
Check out how to write Markdown for multi-line code!

2017-09-29 09:53 UTC, salman-bhai commented on Scala/README.md
> +    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
Replace the entire thing with this
(```)
Check out how to write Markdown for multi-line code!

2017-09-29 18:17 UTC, grrttedwards commented
Updated markdown to use "multi-line" markdown for the shell commands.

2017-09-29 18:23 UTC, grrttedwards commented
If the merge could wait until tomorrow, that would be cool :) 
I didn't know Hacktoberfest was ONLY Oct 1-31 :( My other PR [#125](https://github.com/salman-bhai/hello-world/pull/125) was merged today.

2017-09-29 19:53 UTC, salman-bhai commented
Not a problem! We'll wait. Just make sure you've referenced the Issue!

2017-09-29 19:57 UTC, grrttedwards commented
Fixes issue #133

2017-09-30 05:37 UTC, sbshah97 approved these changes

2017-10-01 04:35 UTC, merged