Update readme python
salman-bhai/hello-world pull request #144
Opened 2017-10-01 14:17 UTC by Tony133

Update Readme

2017-10-01 18:24 UTC, grrttedwards commented on PHP/README.md
> +1. Since apache and PHP come packaged with Max OS no need to install manually again.
There's a typo here "Max OS"

2017-10-01 18:42 UTC, Tony133 commented on PHP/README.md
> +1. Since apache and PHP come packaged with Max OS no need to install manually again.
I fixed 

thanks

Tony133

2017-10-02 06:58 UTC, sbshah97 requested changes
Reference the Issues that you are solving this PR! I see that you have changes three different files! Make sure you reference those Issues!

2017-10-03 10:43 UTC, salman-bhai commented
Any problems here?

2017-10-03 18:07 UTC, salman-bhai commented
Any updates @Tony133

2017-10-03 20:08 UTC, Tony133 commented
Hi, Sorry if I did not answer you but I did not have time these days

2017-10-04 04:01 UTC, sbshah97 approved these changes

2017-10-04 04:01 UTC, merged