Add shell (sh)
salman-bhai/hello-world pull request #156
Opened 2017-10-02 08:32 UTC by valkheim

2017-10-02 09:39 UTC, sbshah97 requested changes
Reference the Issue by adding the Pull Description.

2017-10-02 09:42 UTC, salman-bhai commented
Also any particular reasons to put she since Bash is already there.

2017-10-02 09:47 UTC, valkheim commented
sh is a specification, not an implementation. For some historical reasons it is oftenly a symlink to another shell program. There are multiple reasons why we should always have a sh running.
It is standardized and easy to learn. But most of all, it is portable across posix systems.

2017-10-02 09:49 UTC, sbshah97 requested changes
Make changes accordingly.

2017-10-02 09:49 UTC, salman-bhai commented on sh/README.md
> +
Explain how to setup in Windows, Linux and MacOS. Windows has set up a new bash installer. Make sure you mention about it.

2017-10-02 09:49 UTC, salman-bhai commented on sh/README.md
> +$> ./hello.sh
You need to give permissions to run the file using `chmod +x hello.sh`

2017-10-02 09:49 UTC, salman-bhai commented on sh/hello.sh
> +echo Hello World
Use double quotes.

2017-10-02 11:24 UTC, valkheim commented
Thanks for having noticed these issues

2017-10-02 11:45 UTC, sbshah97 requested changes
Hi, kindly reference the Issue that you are resolving and then I'll merge the PR! Make sure you write Closes `#<Issue Number>` in the PR Description!
In case an Issue isn't created, please create that and then send in the PR!

2017-10-03 10:43 UTC, salman-bhai commented
Any problems here?

2017-10-03 17:46 UTC, sbshah97 approved these changes
Looks good. Well done!

2017-10-03 17:46 UTC, merged