Added Jade language
salman-bhai/hello-world pull request #189
Opened 2018-03-21 07:15 UTC by arfatbk

Added hello world template for Jade

2018-03-21 10:34 UTC, sbshah97 requested changes
Make the required changes in the README and I'll merge your PR!

2018-03-21 10:34 UTC, salman-bhai commented on Jade/README.md
> +### Jade is a node templating engine mostly used for generating plain HTML files
Maybe you can remove the `###` here

2018-03-21 10:34 UTC, salman-bhai commented on Jade/README.md
> +##### 2.Write your `Jade code`using any text editor, like
Maybe you can remove the `#####` here and replace it with `*`

2018-03-21 10:34 UTC, salman-bhai commented on Jade/README.md
> +##### 3. Save file with extension `.jade`
Maybe you can remove the `#####` here and replace it with `*`

2018-03-21 10:34 UTC, salman-bhai commented on Jade/README.md
> +##### 1. Download and install jade from [Jade-lang.com](jade-lang.com) via npm as below
Maybe you can remove the `#####` here and replace it with `*`

2018-03-21 10:34 UTC, salman-bhai commented on Jade/README.md
> +##### 4. Compile code to generate plain HTML using this command
Maybe you can remove the `#####` here and replace it with `*`

2018-03-21 10:34 UTC, salman-bhai commented on Jade/README.md
> +##### Now you have `index.html` file, if you done everything correctly, You can open this `index.html` file in browser by double clicking it.
Maybe you can remove the `#####` here and replace it with `*`

2018-03-21 15:28 UTC, arfatbk reviewed
Updated README.md. This might do

2018-03-21 15:52 UTC, sbshah97 reviewed
One last change :p

2018-03-21 15:52 UTC, salman-bhai commented on Jade/README.md
> +### Jade is a node templating engine mostly used for generating plain HTML files
I think you missed this!

2018-03-25 03:18 UTC, arfatbk commented
Do you want me to remove headings and make them bullets???

2018-03-25 13:59 UTC, sbshah97 approved these changes

2018-03-25 13:59 UTC, merged

2018-03-25 13:59 UTC, salman-bhai commented
I think it's fine! Good work! Thank you for contributing!